# Generated by Django 3.0.4 on 2020-05-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('measurement', models.CharField(choices=[('l', 'Liter'), ('cm', 'Centmieters'), ('pc', 'Piece')], max_length=2)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProductType')),
            ],
        ),
    ]
