# Generated by Django 3.0.4 on 2020-05-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='measurement',
        ),
    ]
