# Generated by Django 3.0.4 on 2020-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_products_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='measurement',
            field=models.CharField(choices=[('l', 'Liter'), ('cm', 'Centmieters'), ('pc', 'Piece')], max_length=2, null=True),
        ),
    ]
