# Generated by Django 3.0.4 on 2020-05-14 21:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_products_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parteners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('registrationNr', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('contactPerson', models.CharField(max_length=35)),
                ('manager', models.CharField(max_length=35)),
            ],
        ),
    ]
