# Generated by Django 3.0.4 on 2020-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_orderdetails_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='value',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
    ]
