# Generated by Django 3.0.4 on 2020-05-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200515_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='value',
        ),
    ]
