# Generated by Django 3.0.4 on 2020-05-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_orders_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
    ]
